kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30001
        hostPort: 80
networking:
  disableDefaultCNI: true
  podSubnet: "172.16.0.0/12"
